import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  FiBookOpen, FiCheck, FiChevronDown, FiChevronLeft, FiChevronRight, FiChevronUp,
  FiCopy, FiDownload, FiEdit3, FiEye, FiFilm, FiImage, FiLayers, FiMove, FiMusic,
  FiPause, FiPlay, FiPlus, FiSave, FiSettings, FiTrash2, FiUpload, FiUser, FiX,
} from "react-icons/fi";
import { useApi } from "./api.jsx";
import { Button, Empty, Field, IconButton, ListButton, Pane, Status, downloadUrl, useDebounced } from "./ui.jsx";

const blankScene = () => ({ speakerName: "Speaker", speakerActorId: "USER_ADMIN_NULL_NULL", dialogue: "New dialogue", voiceLine: "", background: "", music: "", transition: "FADE", fadeTime: 1, dimActors: false, effects: [], actors: [] });

export function StoryApp() {
  const { basePath, request } = useApi();
  const [catalog, setCatalog] = useState(null);
  const [savedProjects, setSavedProjects] = useState([]);
  const [savedId, setSavedId] = useState("");
  const [category, setCategory] = useState("EC_MAINSTREAM");
  const [episodeId, setEpisodeId] = useState("");
  const [layout, setLayout] = useState(null);
  const [definition, setDefinition] = useState(null);
  const [stages, setStages] = useState([]);
  const [selected, setSelected] = useState(null);
  const [baseDetail, setBaseDetail] = useState(null);
  const [mode, setMode] = useState("stages");
  const [frameIndex, setFrameIndex] = useState(0);
  const [selection, setSelection] = useState({ type: "frame" });
  const [playing, setPlaying] = useState(false);
  const [project, setProject] = useState({ id: "my-episode-mod", name: "My Episode Mod" });
  const [pan, setPan] = useState({ x: 0, y: 0 });
  const [output, setOutput] = useState("Loading Story:Side");
  const [error, setError] = useState("");

  const episodes = useMemo(() => (catalog?.episodes || []).filter((item) => item.category === category), [catalog, category]);
  const selectedStage = selected?.source === "mod" ? stages[selected.index] : null;
  const scenes = selectedStage ? (selectedStage.cutsceneReadOnly ? selectedStage.previewScenes || [] : selectedStage.scenes || []) : baseDetail ? flattenCutscenes(baseDetail.cutscenes) : [];
  const frame = scenes[frameIndex] || null;

  const loadProjects = useCallback(async () => { const value = (await request("episode-maker/projects")).projects; setSavedProjects(value); return value; }, [request]);
  useEffect(() => { Promise.all([request("episode-maker/catalog"), loadProjects()]).then(([value, projects]) => { setCatalog(value); const requested = new URLSearchParams(location.search).get("project"); if (requested && projects.some((item) => item.id === requested)) openProject(requested); else { const first = value.episodes.find((item) => item.category === category); if (first) setEpisodeId(String(first.id)); } }).catch((value) => setError(value.message)); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (!catalog || !episodeId) return; request(`episode-maker/layout?episodeId=${encodeURIComponent(episodeId)}&category=${encodeURIComponent(category)}`, { title: `Episode ${episodeId} layout` }).then((value) => { setLayout(value); setDefinition((current) => current?.episodeId === value.episode.definition?.episodeId ? current : structuredClone(value.episode.definition)); setPan({ x: 0, y: 0 }); if (selected?.source === "base") { setSelected(null); setBaseDetail(null); } if (value.episode.custom && !stages.length) setMode("episode"); }).catch((value) => setError(value.message)); }, [catalog, episodeId, category, request]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (!playing || !scenes.length) return; const timer = setInterval(() => setFrameIndex((index) => { if (index >= scenes.length - 1) { setPlaying(false); return index; } return index + 1; }), 2600); return () => clearInterval(timer); }, [playing, scenes.length]);

  function selectCategory(next) { setCategory(next); const first = (catalog?.episodes || []).find((item) => item.category === next); setEpisodeId(first ? String(first.id) : ""); setSelected(null); setBaseDetail(null); }
  function updateStage(patch) { if (!selectedStage) return; setStages((current) => current.map((stage, index) => index === selected.index ? { ...stage, ...patch } : stage)); }
  function updateScenes(next) { if (!selectedStage || selectedStage.cutsceneReadOnly) return; updateStage({ scenes: next }); }
  function updateFrame(patch) { if (!frame || selectedStage?.cutsceneReadOnly || selected?.source === "base") return; const next = scenes.map((item, index) => index === frameIndex ? { ...item, ...patch } : item); updateScenes(next); }

  async function selectNode(node) {
    setSelected(node); setFrameIndex(0); setSelection({ type: "frame" }); setPlaying(false); setError("");
    if (node.source === "mod") { setBaseDetail(null); return; }
    try { setBaseDetail(await request(`episode-maker/stage?stageId=${node.stage.stageId}&episodeId=${episodeId}&category=${encodeURIComponent(category)}&difficulty=${node.stage.difficulty}`, { title: `Stage ${node.stage.stageId}` })); }
    catch (value) { setError(value.message); }
  }

  async function suggestion(difficulty = "NORMAL") {
    for (let offset = stages.length; offset < 50; offset += 1) {
      const value = await request(`episode-maker/suggest?episodeId=${episodeId}&category=${encodeURIComponent(category)}&offset=${offset}&difficulty=${difficulty}`, { title: `New ${difficulty.toLowerCase()} stage` });
      if (!stages.some((stage) => stage.stageId === value.stageId || stage.dungeonId === value.dungeonId || stage.cutsceneId === value.cutsceneId || stage.difficulty === value.difficulty && stage.actId === value.actId && stage.stageIndex === value.stageIndex)) return value;
    }
    throw new Error("This project already uses all 50 generated stage slots.");
  }

  async function addStage(copy, insertionIndex = stages.length) {
    try {
      const source = copy ? selectedStage : null;
      const value = await suggestion(source?.difficulty || "NORMAL");
      const stage = fromSuggestion(value, source ? `${source.title} Copy` : `New Story Stage ${stages.length + 1}`, source?.scenes ? structuredClone(source.scenes) : [blankScene()], definition);
      if (source) Object.assign(stage, { stageDescription: source.stageDescription, stageCharacter: source.stageCharacter, background: source.background, music: source.music, actBackground: source.actBackground, episodeThumbnail: source.episodeThumbnail, dungeonIcon: source.dungeonIcon });
      if (insertionIndex < stages.length) { const previous = stages[Math.max(0, insertionIndex - 1)]; stage.stageIndex = previous.stageIndex + 1; stage.stageUiNumber = previous.stageUiNumber + 1; }
      setStages((current) => [...current.slice(0, insertionIndex), stage, ...current.slice(insertionIndex)]);
      setSelected({ source: "mod", index: insertionIndex }); setMode("stages"); setFrameIndex(0);
    } catch (value) { setError(value.message); }
  }

  async function cloneBase() {
    if (!baseDetail?.raw?.dungeon) return setError("This shared non-dungeon stage cannot be safely cloned.");
    try {
      const value = await suggestion(baseDetail.placement.difficulty);
      const stage = fromSuggestion(value, `${baseDetail.clientUi.title || baseDetail.name} Copy`, [], definition);
      Object.assign(stage, { operation: "clone", sourceObjectId: baseDetail.objectId, sourceStageId: baseDetail.ids.stageId, sourceEpisodeId: baseDetail.placement.episodeId, sourceCategory: baseDetail.placement.category, sourceDifficulty: baseDetail.placement.difficulty, cutsceneReadOnly: true, stageDescription: baseDetail.clientUi.description || baseDetail.clientUi.title || baseDetail.name, stageCharacter: baseDetail.clientUi.avatar || stage.stageCharacter, background: baseDetail.override.background || "CAFE", music: baseDetail.override.music || "", actBackground: baseDetail.clientUi.actBackground || "", episodeThumbnail: baseDetail.clientUi.episodeThumbnail || "", dungeonIcon: baseDetail.clientUi.dungeonIcon || "", cutsceneId: 0, cutsceneStrId: "", scenes: [], previewScenes: flattenCutscenes(baseDetail.cutscenes) });
      setStages((current) => [...current, stage]); setSelected({ source: "mod", index: stages.length }); setMode("stages");
    } catch (value) { setError(value.message); }
  }

  function editOverride(fork = false) {
    if (!baseDetail) return;
    const existing = stages.findIndex((stage) => stage.operation === "override" && stage.baseObjectId === baseDetail.objectId);
    if (existing >= 0) { setSelected({ source: "mod", index: existing }); if (fork) forkCutscene(existing); return; }
    const stage = { ...structuredClone(baseDetail.override), baseSnapshot: structuredClone(baseDetail.override), previewScenes: flattenCutscenes(baseDetail.cutscenes) };
    if (fork) { stage.forkCutscenes = true; stage.cutsceneReadOnly = false; stage.scenes = structuredClone(stage.previewScenes); }
    setStages((current) => [...current, stage]); setSelected({ source: "mod", index: stages.length }); setFrameIndex(0); setMode(fork ? "cutscene" : "stages");
  }

  function forkCutscene(index = selected?.index) {
    const stage = stages[index]; if (!stage) return;
    setStages((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, forkCutscenes: true, cutsceneReadOnly: false, scenes: structuredClone(item.previewScenes || []) } : item));
    setSelected({ source: "mod", index }); setFrameIndex(0); setMode("cutscene");
  }

  function deleteStage() {
    if (!selectedStage) return;
    const label = selectedStage.operation === "override" ? "Remove this override and restore the base stage?" : `Delete ${selectedStage.title} from this project?`;
    if (!confirm(label)) return;
    setStages((current) => current.filter((_, index) => index !== selected.index)); setSelected(null); setFrameIndex(0); setMode("stages");
  }

  function moveStage(direction) {
    if (!selectedStage || selectedStage.operation === "override") return;
    const indexes = stages.map((stage, index) => ({ stage, index })).filter((item) => item.stage.operation !== "override" && item.stage.difficulty === selectedStage.difficulty && item.stage.actId === selectedStage.actId).sort((a, b) => a.stage.stageIndex - b.stage.stageIndex).map((item) => item.index);
    const position = indexes.indexOf(selected.index); const target = indexes[position + direction]; if (target == null) return;
    setStages((current) => { const next = structuredClone(current); [next[selected.index].stageIndex, next[target].stageIndex] = [next[target].stageIndex, next[selected.index].stageIndex]; [next[selected.index].stageUiNumber, next[target].stageUiNumber] = [next[target].stageUiNumber, next[selected.index].stageUiNumber]; return next; });
    setSelected({ source: "mod", index: target });
  }

  async function openProject(id = savedId) {
    if (!id) return;
    try {
      const result = await request(`episode-maker/project?id=${encodeURIComponent(id)}`, { title: id });
      const authoring = result.authoring; const sourceStages = Array.isArray(authoring.stages) ? authoring.stages : [authoring]; const first = sourceStages[0];
      setSavedId(result.manifest.id); setProject({ id: result.manifest.id, name: result.manifest.name }); setCategory(authoring.category || first?.placement.category || "EC_MAINSTREAM"); setEpisodeId(String(authoring.episodeId || first?.placement.episodeId || "")); setDefinition(structuredClone(authoring.episode || definition));
      setStages(sourceStages.map(fromAuthoring)); setSelected(sourceStages.length ? { source: "mod", index: 0 } : null); setFrameIndex(0); setMode(sourceStages.length ? "stages" : "episode"); setOutput(`Loaded ${result.manifest.name} with ${sourceStages.length} stages.`);
    } catch (value) { setError(value.message); }
  }

  async function save(download, sendToLoader = false) {
    if (stages.some((stage) => !stage.cutsceneReadOnly && (!Array.isArray(stage.scenes) || !stage.scenes.length))) return setError("Every editable cutscene stage needs at least one dialogue frame.");
    try {
      const exported = stages.map((stage) => { const value = structuredClone(stage); delete value.previewScenes; delete value.baseSnapshot; return value; });
      const result = await request("episode-maker/create", { method: "POST", body: { projectId: project.id.trim(), projectName: project.name.trim(), category, episodeId: Number(episodeId), episode: definition || undefined, stages: exported }, title: project.name });
      await loadProjects(); setSavedId(result.project.manifest.id); setOutput(`${result.authoring.title} saved with ${result.authoring.stages.length} stages.`); setError("");
      if (sendToLoader) { const report = await request(`mods/${encodeURIComponent(result.project.manifest.id)}/validate`); if (!report.ok) throw new Error(report.errors.map((item) => item.message || item).join("\n") || "The Story:Side mod did not validate."); location.href = `${basePath}?view=loader`; }
      else if (download) location.href = downloadUrl(basePath, result.project.manifest.id);
    } catch (value) { setError(value.message); }
  }

  const canEditCutscene = selectedStage && !selectedStage.cutsceneReadOnly;
  return <section className="panel story-panel"><div className="story-topbar"><div className="mode-tabs"><Button icon={FiSettings} className={mode === "episode" ? "active" : "ghost"} onClick={() => setMode("episode")}>Episode</Button><Button icon={FiLayers} className={mode === "stages" ? "active" : "ghost"} onClick={() => setMode("stages")}>Stages</Button><Button icon={FiFilm} className={mode === "cutscene" ? "active" : "ghost"} disabled={!scenes.length} onClick={() => setMode("cutscene")}>Cutscene</Button></div><div className="button-row"><Button icon={FiPlus} onClick={() => addStage(false)}>Stage</Button><Button icon={FiUpload} onClick={() => save(false, true)}>Mod:Side</Button><Button icon={FiDownload} className="primary" onClick={() => save(true)}>Export ZIP</Button></div></div>
    <div className="story-projectbar"><Field label="Project"><select value={savedId} onChange={(event) => setSavedId(event.target.value)}><option value="">New project</option>{savedProjects.map((item) => <option key={item.id} value={item.id}>{item.name} ({item.stageCount})</option>)}</select></Field><Button icon={FiBookOpen} onClick={() => openProject()} disabled={!savedId}>Open</Button><Field label="Category"><select value={category} onChange={(event) => selectCategory(event.target.value)}><option value="EC_MAINSTREAM">Mainstream</option><option value="EC_SIDESTORY">Substream</option></select></Field><Field label="Episode"><select value={episodeId} onChange={(event) => { setEpisodeId(event.target.value); setSelected(null); }}>{episodes.map((item) => <option key={`${item.category}-${item.id}`} value={item.id}>{item.label}</option>)}</select></Field><Field label="Project ID"><input required value={project.id} onChange={(event) => setProject({ ...project, id: event.target.value })} /></Field><Field label="Name"><input required value={project.name} onChange={(event) => setProject({ ...project, name: event.target.value })} /></Field></div>
    {error && <Status kind="bad">{error}</Status>}
    <div className="story-studio"><main className="story-canvas-column">{mode === "episode" ? <EpisodeOverview definition={definition} stages={stages} /> : mode === "stages" ? <StageLayout baseStages={layout?.stages || []} stages={stages} selected={selected} onSelect={selectNode} pan={pan} setPan={setPan} bounds={definition} onReorder={(from, to) => { setSelected({ source: "mod", index: from }); const direction = stages[from].stageIndex < stages[to].stageIndex ? 1 : -1; moveStage(direction); }} /> : <CutsceneWorkspace catalog={catalog} stage={selectedStage} scene={frame} frameIndex={frameIndex} scenes={scenes} selection={selection} setSelection={setSelection} onFrame={setFrameIndex} playing={playing} setPlaying={setPlaying} basePath={basePath} />}
      {mode !== "episode" && <div className="playback"><IconButton icon={FiChevronLeft} label="Previous" disabled={mode === "cutscene" ? frameIndex <= 0 : false} onClick={() => mode === "cutscene" ? setFrameIndex(Math.max(0, frameIndex - 1)) : navigateNode(-1, layout, stages, selected, selectNode)} /><IconButton icon={playing ? FiPause : FiPlay} label={playing ? "Pause" : "Play"} className="primary" disabled={!scenes.length} onClick={() => { if (mode !== "cutscene") setMode("cutscene"); setPlaying(!playing); }} /><span>{mode === "cutscene" ? `${scenes.length ? frameIndex + 1 : 0} / ${scenes.length}` : `${(layout?.stages?.length || 0) + stages.length} stages`}</span><IconButton icon={FiChevronRight} label="Next" disabled={mode === "cutscene" ? frameIndex >= scenes.length - 1 : false} onClick={() => mode === "cutscene" ? setFrameIndex(Math.min(scenes.length - 1, frameIndex + 1)) : navigateNode(1, layout, stages, selected, selectNode)} /></div>}
      {mode === "cutscene" && <Timeline scenes={scenes} index={frameIndex} readOnly={!canEditCutscene} onSelect={(index) => { setFrameIndex(index); setSelection({ type: "frame" }); }} onAdd={() => { updateScenes([...scenes, blankScene()]); setFrameIndex(scenes.length); }} />}
    </main><aside className="story-inspectors">{mode === "episode" ? <EpisodeInspector definition={definition} setDefinition={setDefinition} catalog={catalog} /> : mode === "stages" ? <StageInspector selected={selected} stage={selectedStage} detail={baseDetail} catalog={catalog} update={updateStage} onInsert={() => addStage(false, selected?.source === "mod" ? selected.index + 1 : stages.length)} onCopy={() => addStage(true)} onEarlier={() => moveStage(-1)} onLater={() => moveStage(1)} onDelete={deleteStage} onEdit={() => selected?.source === "base" ? editOverride(false) : setMode("cutscene")} onClone={cloneBase} onFork={() => selected?.source === "base" ? editOverride(true) : forkCutscene()} onPreview={() => setMode("cutscene")} /> : <CutsceneInspector scene={frame} scenes={scenes} index={frameIndex} selection={selection} setSelection={setSelection} readOnly={!canEditCutscene} catalog={catalog} updateFrame={updateFrame} updateScenes={updateScenes} setFrameIndex={setFrameIndex} />}
      <pre className="story-output">{output}</pre></aside></div>
    <StoryDatalists catalog={catalog} />
  </section>;
}

function EpisodeOverview({ definition, stages }) { return <div className="episode-overview"><FiBookOpen /><h2>{definition?.title || "Episode"}</h2><p>{definition?.description || "Configure the episode client UI, then add stages."}</p><div><span>{definition?.actCount || 0} Normal acts</span><span>{definition?.hardMode?.enabled ? `${definition.hardMode.actCount} Hard acts` : "Hard mode disabled"}</span><span>{stages.length} modded stages</span></div></div>; }

function EpisodeInspector({ definition, setDefinition, catalog }) {
  if (!definition) return <Pane title="Episode settings"><Empty>Select an episode.</Empty></Pane>;
  const update = (path, value) => setDefinition(setPath(definition, path, value));
  return <><Pane title="Episode UI" meta={definition.custom ? "New Episode 16 definition" : "Existing episode override"}><div className="inspector-form"><TextField label="Title" value={definition.title} onChange={(value) => update(["title"], value)} /><TextField label="Name" value={definition.name} onChange={(value) => update(["name"], value)} /><TextField label="Description" value={definition.description} onChange={(value) => update(["description"], value)} textarea /><TextField label="Extra description" value={definition.extraDescription} onChange={(value) => update(["extraDescription"], value)} textarea /><NumberField label="Act count" value={definition.actCount} min={1} max={50} onChange={(value) => update(["actCount"], value)} /><NumberField label="Group ID" value={definition.groupId} min={1} onChange={(value) => update(["groupId"], value)} /><AssetField label="Stage viewer UI" kind="image" value={definition.stageViewerPrefab} onChange={(value) => update(["stageViewerPrefab"], value)} catalog={catalog} /><AssetField label="Episode art" kind="image" value={definition.thumbnail} onChange={(value) => update(["thumbnail"], value)} catalog={catalog} /><AssetField label="Act background" kind="image" value={definition.actBackground} onChange={(value) => update(["actBackground"], value)} catalog={catalog} /><AssetField label="Music" kind="music" value={definition.backgroundMusic} onChange={(value) => update(["backgroundMusic"], value)} catalog={catalog} /><SelectField label="Scroll direction" value={definition.scrollType} options={["HORIZONTAL", "VERTICAL"]} onChange={(value) => update(["scrollType"], value)} /><CheckField label="Hide act tabs" checked={definition.hideActTabs} onChange={(value) => update(["hideActTabs"], value)} /><CheckField label="No collection cutscene" checked={definition.noCollectionCutscene} onChange={(value) => update(["noCollectionCutscene"], value)} /><TextField label="Normal open tag" value={definition.openTag} disabled={!definition.custom} onChange={(value) => update(["openTag"], value)} /><TextField label="Collection open tag" value={definition.collectionOpenTag} disabled={!definition.custom} onChange={(value) => update(["collectionOpenTag"], value)} /><TextField label="Connected episode IDs" value={(definition.connectedEpisodeIds || []).join(", ")} onChange={(value) => update(["connectedEpisodeIds"], value.split(",").map(Number).filter(Number.isSafeInteger))} /><NumberField label="Horizontal pan" value={definition.layoutPanX} min={0} max={5000} onChange={(value) => update(["layoutPanX"], value)} /><NumberField label="Vertical pan" value={definition.layoutPanY} min={0} max={5000} onChange={(value) => update(["layoutPanY"], value)} /></div></Pane>
    <Pane title="Summary art" meta="Episode selector and lobby presentation"><div className="inspector-form"><AssetField label="Lobby art" kind="image" value={definition.summary.lobbyResourceId} onChange={(value) => update(["summary", "lobbyResourceId"], value)} catalog={catalog} /><AssetField label="Large art" kind="image" value={definition.summary.bigResourceId} onChange={(value) => update(["summary", "bigResourceId"], value)} catalog={catalog} /><AssetField label="Summary thumbnail" kind="image" value={definition.summary.subResourceId} onChange={(value) => update(["summary", "subResourceId"], value)} catalog={catalog} /><TextField label="Date text" value={definition.summary.dateText} onChange={(value) => update(["summary", "dateText"], value)} /></div><Rewards label="Normal completion rewards" value={definition.completionRewards} onChange={(value) => update(["completionRewards"], value)} /><ResourceChange label="Normal mid-episode music" value={definition.resourceChange} onChange={(value) => update(["resourceChange"], value)} /></Pane>
    <Pane title="Hard mode" meta="Acts, UI, rewards, and collection behavior"><CheckField label="Enable Hard mode" checked={definition.hardMode.enabled} disabled={!definition.custom} onChange={(value) => update(["hardMode", "enabled"], value)} />{definition.hardMode.enabled && <><div className="inspector-form"><NumberField label="Act count" value={definition.hardMode.actCount} min={1} max={50} onChange={(value) => update(["hardMode", "actCount"], value)} /><TextField label="Hard open tag" value={definition.hardMode.openTag} disabled={!definition.custom} onChange={(value) => update(["hardMode", "openTag"], value)} /><AssetField label="Stage viewer UI" kind="image" value={definition.hardMode.stageViewerPrefab} onChange={(value) => update(["hardMode", "stageViewerPrefab"], value)} catalog={catalog} /><AssetField label="Episode art" kind="image" value={definition.hardMode.thumbnail} onChange={(value) => update(["hardMode", "thumbnail"], value)} catalog={catalog} /><AssetField label="Music" kind="music" value={definition.hardMode.backgroundMusic} onChange={(value) => update(["hardMode", "backgroundMusic"], value)} catalog={catalog} /><SelectField label="Scroll direction" value={definition.hardMode.scrollType} options={["HORIZONTAL", "VERTICAL"]} onChange={(value) => update(["hardMode", "scrollType"], value)} /><CheckField label="Hide act tabs" checked={definition.hardMode.hideActTabs} onChange={(value) => update(["hardMode", "hideActTabs"], value)} /><CheckField label="No collection cutscene" checked={definition.hardMode.noCollectionCutscene} onChange={(value) => update(["hardMode", "noCollectionCutscene"], value)} /></div><Rewards label="Hard completion rewards" value={definition.hardMode.completionRewards} onChange={(value) => update(["hardMode", "completionRewards"], value)} /><ResourceChange label="Hard mid-episode music" value={definition.hardMode.resourceChange} onChange={(value) => update(["hardMode", "resourceChange"], value)} /></>}</Pane></>;
}

function StageLayout({ baseStages, stages, selected, onSelect, pan, setPan, bounds, onReorder }) {
  const canvasRef = useRef(null); const containerRef = useRef(null); const drag = useRef(null);
  const [difficulty, setDifficulty] = useState("NORMAL");
  const [actId, setActId] = useState(1);
  const nodes = useMemo(() => { const overrides = new Set(stages.filter((stage) => stage.operation === "override").map((stage) => `${stage.stageId}:${stage.difficulty}`)); return baseStages.filter((stage) => !overrides.has(`${stage.stageId}:${stage.difficulty}`)).map((stage) => ({ source: "base", stage })).concat(stages.map((stage, index) => ({ source: "mod", stage, index }))).sort((a, b) => Number(a.stage.difficulty === "HARD") - Number(b.stage.difficulty === "HARD") || a.stage.actId - b.stage.actId || a.stage.stageIndex - b.stage.stageIndex); }, [baseStages, stages]);
  const difficulties = nodes.some((node) => node.stage.difficulty === "HARD") || bounds?.hardMode?.enabled ? ["NORMAL", "HARD"] : ["NORMAL"];
  const configuredActs = difficulty === "HARD" ? bounds?.hardMode?.actCount : bounds?.actCount;
  const actCount = Math.max(1, Number(configuredActs) || 0, ...nodes.filter((node) => (node.stage.difficulty || "NORMAL") === difficulty).map((node) => Number(node.stage.actId) || 0));
  const activeNodes = nodes.filter((node) => (node.stage.difficulty || "NORMAL") === difficulty && Number(node.stage.actId) === actId);
  const positioned = useMemo(() => positionNodes(activeNodes, pan), [activeNodes, pan]);
  useEffect(() => { if (!selected?.stage) return; setDifficulty(selected.stage.difficulty || "NORMAL"); setActId(Number(selected.stage.actId) || 1); }, [selected]);
  useEffect(() => drawStageCanvas(canvasRef.current, positioned), [positioned]);
  function pointerDown(event, node) { event.currentTarget.setPointerCapture(event.pointerId); drag.current = { node, startX: event.clientX, startY: event.clientY, pan, moved: false }; }
  function pointerMove(event) { const current = drag.current; if (!current) return; const dx = event.clientX - current.startX, dy = event.clientY - current.startY; current.moved ||= Math.abs(dx) + Math.abs(dy) > 4; if (current.node) return; const limitX = Number(bounds?.layoutPanX || 960), limitY = Number(bounds?.layoutPanY || 480); setPan({ x: Math.max(-limitX, Math.min(limitX, current.pan.x + dx * 1.4)), y: Math.max(-limitY, Math.min(limitY, current.pan.y + dy * 1.4)) }); }
  function pointerUp(event) { const current = drag.current; if (!current) return; drag.current = null; if (!current.node) return; if (!current.moved) return onSelect(current.node); if (current.node.source !== "mod" || current.node.stage.operation === "override") return; const container = containerRef.current; if (!container) return; const rect = container.getBoundingClientRect(); const target = positioned.filter((item) => item.source === "mod" && item.index !== current.node.index && item.stage.operation !== "override" && item.stage.difficulty === current.node.stage.difficulty && item.stage.actId === current.node.stage.actId).sort((a, b) => Math.abs(event.clientX - rect.left - (a.x + a.w / 2) * rect.width / 1280) - Math.abs(event.clientX - rect.left - (b.x + b.w / 2) * rect.width / 1280))[0]; if (target) onReorder(current.node.index, target.index); }
  return <div ref={containerRef} className="stage-layout-canvas" onPointerDown={(event) => { if (event.target === event.currentTarget || event.target === canvasRef.current) pointerDown(event, null); }} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={() => { drag.current = null; }}><canvas ref={canvasRef} width="1280" height="720" aria-label="Stage layout; drag empty space to pan" /><header className="stage-layout-header"><small>{difficulty === "HARD" ? "Hard" : "Normal"} operation</small><strong>{bounds?.title || "Episode stages"}</strong><span>Act {actId} · {activeNodes.length} stages</span></header>{positioned.map((node) => <button key={`${node.source}-${node.stage.stageId}-${node.stage.difficulty}-${node.index ?? "base"}`} type="button" className={`stage-node ${node.source} ${isSelected(node, selected) ? "selected" : ""}`} style={{ left: `${node.x / 12.8}%`, top: `${node.y / 7.2}%`, width: `${node.w / 12.8}%`, height: `${node.h / 7.2}%` }} onPointerDown={(event) => { event.stopPropagation(); pointerDown(event, node); }} onPointerMove={pointerMove} onPointerUp={pointerUp} onClick={() => onSelect(node)}><strong>{node.stage.actId}-{node.stage.stageUiNumber}</strong><small>{node.stage.title || (node.source === "mod" ? "Mod stage" : "Base stage")}</small>{node.stage.operation === "clone" && <FiCopy />}</button>)}<nav className="stage-layout-tabs" aria-label="Stage categories"><div className="difficulty-tabs">{difficulties.map((item) => <Button key={item} className={difficulty === item ? "active" : "ghost"} onClick={() => { setDifficulty(item); setActId(1); setPan({ x: 0, y: 0 }); }}>{item === "HARD" ? "Hard" : "Normal"}</Button>)}</div><div className="act-tabs">{Array.from({ length: actCount }, (_, index) => index + 1).map((item) => <Button key={item} className={actId === item ? "active" : "ghost"} onClick={() => { setActId(item); setPan({ x: 0, y: 0 }); }}>Act {item}</Button>)}</div></nav></div>;
}

function StageInspector({ selected, stage, detail, catalog, update, onInsert, onCopy, onEarlier, onLater, onDelete, onEdit, onClone, onFork, onPreview }) {
  if (!selected) return <Pane title="Stage details"><Empty>Select a stage node.</Empty></Pane>;
  if (selected.source === "base") return <><Pane title={selected.stage.title} meta="Base game · protected">{detail ? <div className="inspector-form"><ReadField label="Type" value={detail.kind} /><ReadField label="Stage string ID" value={detail.ids.stageStrId} /><ReadField label="Dungeon string ID" value={detail.ids.dungeonStrId} /><ReadField label="Avatar" value={detail.clientUi.avatar} /><ReadField label="Dungeon icon" value={detail.clientUi.dungeonIcon} /><ReadField label="Cutscenes" value={detail.cutscenes.length} /><div className="button-row wide"><Button icon={FiEdit3} className="primary" onClick={onEdit}>Edit override</Button><Button icon={FiCopy} onClick={onClone} disabled={!detail.raw.dungeon}>Clone</Button>{Boolean(detail.cutscenes.length) && <><Button icon={FiFilm} onClick={onFork} disabled={!detail.raw.dungeon}>Fork cutscene</Button><Button icon={FiEye} onClick={onPreview}>Preview</Button></>}</div></div> : <Empty>Loading complete stage data.</Empty>}</Pane>{detail && <Pane title="Placement and linked data" meta="Read-only"><div className="inspector-form"><ReadField label="Difficulty" value={detail.placement.difficulty} /><ReadField label="Act" value={detail.placement.actId} /><ReadField label="Index" value={detail.placement.stageIndex} /><ReadField label="Stage number" value={detail.placement.stageNumber} /><ReadField label="Stage ID" value={detail.ids.stageId} /><ReadField label="Dungeon ID" value={detail.ids.dungeonId} /><ReadField label="Unlock type" value={detail.unlock.requirementType} /><ReadField label="Unlock value" value={detail.unlock.requirementValue} /></div><details><summary>Raw stage records</summary><pre>{JSON.stringify(detail.raw, null, 2)}</pre></details></Pane>}</>;
  const locked = stage.operation === "override";
  return <><Pane title={stage.title || "Custom stage"} meta={stage.forkCutscenes ? "Source-preserving cutscene fork" : stage.operation === "override" ? "Base override" : stage.operation === "clone" ? "Stage clone" : "New stage"}><div className="inspector-form"><TextField label="Title" value={stage.title} onChange={(value) => update({ title: value })} /><TextField label="Description" value={stage.stageDescription} textarea onChange={(value) => update({ stageDescription: value })} /><SelectField label="Difficulty" value={stage.difficulty} disabled={locked} options={["NORMAL", "HARD"]} onChange={(value) => update({ difficulty: value })} /><AssetField label="Avatar" kind="actor" value={stage.stageCharacter} onChange={(value) => update({ stageCharacter: value })} catalog={catalog} /><AssetField label="Background" kind="background" value={stage.background} disabled={locked || stage.operation === "clone"} onChange={(value) => update({ background: value })} catalog={catalog} /><AssetField label="Music" kind="music" value={stage.music} onChange={(value) => update({ music: value })} catalog={catalog} /><AssetField label="Act art" kind="image" value={stage.actBackground} onChange={(value) => update({ actBackground: value })} catalog={catalog} /><AssetField label="Episode art" kind="image" value={stage.episodeThumbnail} onChange={(value) => update({ episodeThumbnail: value })} catalog={catalog} /><AssetField label="Dungeon icon" kind="image" value={stage.dungeonIcon} onChange={(value) => update({ dungeonIcon: value })} catalog={catalog} /></div><div className="button-grid"><Button icon={FiPlus} onClick={onInsert} disabled={locked}>Insert</Button><Button icon={FiCopy} onClick={onCopy} disabled={locked}>Copy</Button><IconButton icon={FiChevronUp} label="Move stage earlier" onClick={onEarlier} disabled={locked} /><IconButton icon={FiChevronDown} label="Move stage later" onClick={onLater} disabled={locked} /><Button icon={FiEdit3} className="primary" onClick={onEdit}>Edit cutscene</Button><Button icon={FiTrash2} className="danger" onClick={onDelete}>{locked ? "Remove override" : "Delete"}</Button></div></Pane>
    <Pane title="Placement and IDs" meta={locked ? "Stable base identities" : "Generated automatically; editable"}><div className="inspector-form"><NumberField label="Act" value={stage.actId} min={1} onChange={(value) => update({ actId: value })} /><NumberField label="Index" value={stage.stageIndex} min={1} onChange={(value) => update({ stageIndex: value })} /><NumberField label="Display number" value={stage.stageUiNumber} min={1} onChange={(value) => update({ stageUiNumber: value })} /><NumberField label="Unlock after" value={stage.unlockDungeonId} min={0} onChange={(value) => update({ unlockDungeonId: value })} /><NumberField label="Stage ID" value={stage.stageId} min={1} disabled={locked} onChange={(value) => update({ stageId: value })} /><NumberField label="Dungeon ID" value={stage.dungeonId} min={1} disabled={locked} onChange={(value) => update({ dungeonId: value })} /><NumberField label="Cutscene ID" value={stage.cutsceneId} min={0} disabled={locked || stage.operation === "clone"} onChange={(value) => update({ cutsceneId: value })} /><TextField label="Stage string ID" value={stage.stageStrId} disabled={locked} onChange={(value) => update({ stageStrId: value })} /><TextField label="Dungeon string ID" value={stage.dungeonStrId} disabled={locked} onChange={(value) => update({ dungeonStrId: value })} /><TextField label="Cutscene string ID" value={stage.cutsceneStrId} disabled={locked || stage.operation === "clone"} onChange={(value) => update({ cutsceneStrId: value })} /></div></Pane></>;
}

function CutsceneWorkspace({ catalog, stage, scene, frameIndex, scenes, selection, setSelection, onFrame, playing, setPlaying, basePath }) {
  if (!scene) return <div className="cutscene-canvas"><Empty>Select a stage with a cutscene.</Empty></div>;
  return <div className="cutscene-canvas"><WebGlScene scene={scene} stage={stage} catalog={catalog} basePath={basePath} /><div className="actor-hotspots">{(scene.actors || []).map((actor, index) => actor.visible !== false && <button key={`${actor.actorId}-${index}`} type="button" className={`actor-hotspot ${selection.type === "actor" && selection.index === index ? "selected" : ""} ${actor.position || "C"}`} aria-label={`Select ${actor.actorId}`} onClick={() => setSelection({ type: "actor", index })} />)}</div><button type="button" className="background-hotspot" aria-label="Select background" onClick={() => setSelection({ type: "background" })} /><div className="fx-chips">{(scene.effects || []).map((effect) => <span key={effect}>{effect}</span>)}</div><div className="dialogue-box" onClick={() => setSelection({ type: "frame" })}>{scene.speakerActorId && <ActorPreview actorId={scene.speakerActorId} catalog={catalog} basePath={basePath} />}<div><strong>{scene.speakerName}</strong><p>{scene.dialogue}</p></div></div></div>;
}

function CutsceneInspector({ scene, scenes, index, selection, setSelection, readOnly, catalog, updateFrame, updateScenes, setFrameIndex }) {
  if (!scene) return <Pane title="Frame"><Empty>Select a cutscene frame.</Empty></Pane>;
  if (readOnly) return <><Pane title={`Frame ${index + 1}`} meta="Read-only until the cutscene is forked"><div className="inspector-form"><ReadField label="Speaker" value={scene.speakerName} /><ReadField label="Actor ID" value={scene.speakerActorId} /><ReadField label="Dialogue" value={scene.dialogue} /><ReadField label="Voice" value={scene.voiceLine} /></div></Pane><Pane title="Source event"><pre>{JSON.stringify(scene.raw || scene, null, 2)}</pre></Pane></>;
  const actor = selection.type === "actor" ? scene.actors?.[selection.index] : null;
  function updateActor(patch) { updateFrame({ actors: scene.actors.map((item, itemIndex) => itemIndex === selection.index ? { ...item, ...patch } : item) }); }
  function addActor() { if ((scene.actors || []).length >= 6) return; updateFrame({ actors: [...(scene.actors || []), { actorId: "USER_ADMIN_NULL_NULL", position: "C", animation: "UNIT_IDLE", visible: true, previewAsset: "" }] }); setSelection({ type: "actor", index: (scene.actors || []).length }); }
  function moveActor(direction) { const target = selection.index + direction; if (target < 0 || target >= scene.actors.length) return; const actors = scene.actors.slice(); [actors[selection.index], actors[target]] = [actors[target], actors[selection.index]]; updateFrame({ actors }); setSelection({ type: "actor", index: target }); }
  function removeActor() { updateFrame({ actors: scene.actors.filter((_, itemIndex) => itemIndex !== selection.index) }); setSelection({ type: "frame" }); }
  function moveFrame(direction) { const target = index + direction; if (target < 0 || target >= scenes.length) return; const next = scenes.slice(); [next[index], next[target]] = [next[target], next[index]]; updateScenes(next); setFrameIndex(target); }
  function copyFrame() { const next = scenes.slice(); next.splice(index + 1, 0, structuredClone(scene)); updateScenes(next); setFrameIndex(index + 1); }
  function removeFrame() { if (scenes.length <= 1) return; updateScenes(scenes.filter((_, itemIndex) => itemIndex !== index)); setFrameIndex(Math.min(index, scenes.length - 2)); }
  return <><Pane title={actor ? actor.actorId : selection.type === "background" ? "Background" : `Frame ${index + 1}`} meta={actor ? `Layer ${selection.index + 1} of ${scene.actors.length}` : selection.type === "background" ? "Canvas layer" : `${scene.actors?.length || 0} actors`}>
    {actor ? <div className="inspector-form"><AssetField label="Actor ID" kind="actor" value={actor.actorId} onChange={(value) => updateActor({ actorId: value })} catalog={catalog} /><SelectField label="Position" value={actor.position || "C"} options={["L", "C", "R"]} onChange={(value) => updateActor({ position: value })} /><TextField label="Mood or animation" value={actor.animation || "UNIT_IDLE"} onChange={(value) => updateActor({ animation: value })} /><TextField label="Custom preview path" value={actor.previewAsset || ""} onChange={(value) => updateActor({ previewAsset: value })} /><CheckField label="Visible in this frame" checked={actor.visible !== false} onChange={(value) => updateActor({ visible: value })} /><div className="button-row wide"><IconButton icon={FiChevronDown} label="Move actor backward" disabled={selection.index === 0} onClick={() => moveActor(-1)} /><IconButton icon={FiChevronUp} label="Move actor forward" disabled={selection.index === scene.actors.length - 1} onClick={() => moveActor(1)} /><Button icon={FiTrash2} className="danger" onClick={removeActor}>Delete actor</Button></div></div> : selection.type === "background" ? <div className="inspector-form"><AssetField label="Background" kind="background" value={scene.background || ""} onChange={(value) => updateFrame({ background: value })} catalog={catalog} /><AssetField label="Music" kind="music" value={scene.music || ""} onChange={(value) => updateFrame({ music: value })} catalog={catalog} /><Button icon={FiPlus} className="wide" onClick={addActor}>Actor</Button></div> : <div className="inspector-form"><TextField label="Speaker" value={scene.speakerName} onChange={(value) => updateFrame({ speakerName: value })} /><AssetField label="Actor ID" kind="actor" value={scene.speakerActorId} onChange={(value) => updateFrame({ speakerActorId: value })} catalog={catalog} /><TextField label="Dialogue" value={scene.dialogue} textarea onChange={(value) => updateFrame({ dialogue: value })} /><AssetField label="Voice" kind="voice" value={scene.voiceLine || ""} onChange={(value) => updateFrame({ voiceLine: value })} catalog={catalog} /><div className="button-grid wide"><Button icon={FiPlus} onClick={addActor}>Actor</Button><IconButton icon={FiChevronUp} label="Move frame earlier" disabled={index === 0} onClick={() => moveFrame(-1)} /><IconButton icon={FiChevronDown} label="Move frame later" disabled={index === scenes.length - 1} onClick={() => moveFrame(1)} /><Button icon={FiCopy} onClick={copyFrame}>Copy</Button><Button icon={FiTrash2} className="danger" disabled={scenes.length <= 1} onClick={removeFrame}>Delete</Button></div></div>}
  </Pane><Pane title="Timing and effects" meta="Frame settings"><div className="inspector-form"><SelectField label="Transition" value={scene.transition || "FADE"} options={["FADE", "CUT"]} onChange={(value) => updateFrame({ transition: value })} /><NumberField label="Fade seconds" value={scene.fadeTime ?? 1} min={0} max={10} step={0.1} onChange={(value) => updateFrame({ fadeTime: value })} /><AssetField label="Background override" kind="background" value={scene.background || ""} onChange={(value) => updateFrame({ background: value })} catalog={catalog} /><AssetField label="Music override" kind="music" value={scene.music || ""} onChange={(value) => updateFrame({ music: value })} catalog={catalog} /><TextField label="Effects in play order" value={(scene.effects || []).join("\n")} textarea onChange={(value) => updateFrame({ effects: value.split(/\r?\n/).map((item) => item.trim()).filter(Boolean) })} /><CheckField label="Dim actors" checked={scene.dimActors === true} onChange={(value) => updateFrame({ dimActors: value })} /></div></Pane></>;
}

function Timeline({ scenes, index, readOnly, onSelect, onAdd }) { return <section className="timeline"><header><div><FiFilm /><strong>Frames</strong><span>{scenes.length ? index + 1 : 0} / {scenes.length}</span></div><Button icon={FiPlus} className="primary" disabled={readOnly} onClick={onAdd}>Frame</Button></header><div className="timeline-scroll">{scenes.map((scene, itemIndex) => <button key={itemIndex} type="button" className={itemIndex === index ? "active" : ""} onClick={() => onSelect(itemIndex)}><strong>{itemIndex + 1}. {scene.speakerName}</strong><span>{scene.dialogue}</span></button>)}</div></section>; }

function WebGlScene({ scene, stage, catalog, basePath }) {
  const canvas = useRef(null);
  useEffect(() => { let cancelled = false; const background = assetRoute(catalog, "background", scene.background || stage?.background || ""); const actors = (scene.actors || []).filter((actor) => actor.visible !== false).map((actor) => ({ ...actor, route: actor.previewAsset ? `${basePath}/api/asset?path=${encodeURIComponent(actor.previewAsset)}` : assetRoute(catalog, "actor", actor.actorId) })); Promise.all([loadImage(background ? routeUrl(basePath, background) : ""), ...actors.map((actor) => loadImage(actor.route ? routeUrl(basePath, actor.route) : ""))]).then(([backgroundImage, ...actorImages]) => { if (!cancelled) drawWebGlScene(canvas.current, backgroundImage, actors.map((actor, index) => ({ ...actor, image: actorImages[index] })), scene.dimActors); }); return () => { cancelled = true; }; }, [scene, stage?.background, catalog, basePath]);
  return <canvas ref={canvas} width="1280" height="720" aria-label="WebGL cutscene preview" />;
}

function ActorPreview({ actorId, catalog, basePath }) { const route = assetRoute(catalog, "actor", actorId); return route ? <img src={routeUrl(basePath, route)} alt={actorId} /> : null; }

function AssetField({ label, kind, value, onChange, catalog, disabled }) { const debounced = useDebounced(value, 300); return <label className="field wide"><span>{label}</span><input value={value || ""} disabled={disabled} list={`story-${kind}-options`} onChange={(event) => onChange(event.target.value)} /><AssetPreview kind={kind} id={debounced} catalog={catalog} /></label>; }
function StoryDatalists({ catalog }) { const values = { actor: catalog?.actors || [], background: catalog?.backgrounds || [], music: catalog?.music || [], voice: catalog?.voices || [], image: catalog?.stageCharacters || [] }; return <>{Object.entries(values).map(([kind, items]) => <datalist id={`story-${kind}-options`} key={kind}>{items.map((item) => { const value = typeof item === "string" ? item : item.id; return value ? <option key={value} value={value} /> : null; })}</datalist>)}</>; }
function AssetPreview({ kind, id, catalog }) { const { basePath, request } = useApi(); const [asset, setAsset] = useState(null); useEffect(() => { setAsset(null); if (!String(id || "").trim()) return; const route = assetRoute(catalog, kind, id); if (route) { setAsset({ found: true, type: kind === "music" || kind === "voice" ? "audio" : "image", url: routeUrl(basePath, route) }); return; } request(`episode-maker/asset?kind=${encodeURIComponent(kind)}&id=${encodeURIComponent(id)}`, { title: id }).then((value) => setAsset(value.found ? { ...value, url: `${basePath}/api/asset?path=${encodeURIComponent(value.path)}` } : { found: false })).catch(() => setAsset({ found: false })); }, [kind, id, catalog, basePath, request]); if (!id) return null; if (!asset) return <small className="asset-preview-text">Resolving asset</small>; if (!asset.found) return <small className="asset-preview-text">No extracted preview</small>; return <span className="field-preview">{asset.type === "audio" ? <audio controls preload="metadata" src={asset.url} /> : <img src={asset.url} alt="" />}</span>; }

function TextField({ label, value, onChange, textarea, disabled }) { return <label className="field wide"><span>{label}</span>{textarea ? <textarea rows="3" value={value || ""} disabled={disabled} onChange={(event) => onChange(event.target.value)} /> : <input value={value || ""} disabled={disabled} onChange={(event) => onChange(event.target.value)} />}</label>; }
function NumberField({ label, value, onChange, min, max, step = 1, disabled }) { return <label className="field"><span>{label}</span><input type="number" value={value ?? ""} min={min} max={max} step={step} disabled={disabled} onChange={(event) => onChange(Number(event.target.value))} /></label>; }
function SelectField({ label, value, options, onChange, disabled }) { return <label className="field"><span>{label}</span><select value={value || options[0]} disabled={disabled} onChange={(event) => onChange(event.target.value)}>{options.map((item) => <option key={item}>{item}</option>)}</select></label>; }
function CheckField({ label, checked, onChange, disabled }) { return <label className="check-field wide"><input type="checkbox" checked={Boolean(checked)} disabled={disabled} onChange={(event) => onChange(event.target.checked)} /><span>{label}</span></label>; }
function ReadField({ label, value }) { return <label className="field read-field"><span>{label}</span><output>{String(value ?? "")}</output></label>; }

function Rewards({ label, value, onChange }) { return <details className="settings-group"><summary>{label}</summary><div className="reward-grid">{(value || []).map((reward, index) => <section key={index}><strong>Tier {index + 1}</strong><NumberField label="Completion rate" value={reward.completeRate} min={0} max={100} onChange={(next) => onChange(value.map((item, itemIndex) => itemIndex === index ? { ...item, completeRate: next } : item))} /><TextField label="Reward type" value={reward.rewardType} onChange={(next) => onChange(value.map((item, itemIndex) => itemIndex === index ? { ...item, rewardType: next } : item))} /><NumberField label="Reward ID" value={reward.rewardId} min={0} onChange={(next) => onChange(value.map((item, itemIndex) => itemIndex === index ? { ...item, rewardId: next } : item))} /><NumberField label="Reward value" value={reward.rewardValue} min={0} onChange={(next) => onChange(value.map((item, itemIndex) => itemIndex === index ? { ...item, rewardValue: next } : item))} /></section>)}</div></details>; }
function ResourceChange({ label, value, onChange }) { return <details className="settings-group"><summary>{label}</summary><div className="inspector-form"><TextField label="Mission condition" value={value?.missionCondition || ""} onChange={(next) => onChange({ ...value, missionCondition: next })} /><NumberField label="Mission value" value={value?.missionValue || 0} min={0} onChange={(next) => onChange({ ...value, missionValue: next })} /><TextField label="Background music" value={value?.backgroundMusic || ""} onChange={(next) => onChange({ ...value, backgroundMusic: next })} /></div></details>; }

function flattenCutscenes(cutscenes = []) { return cutscenes.flatMap((cutscene) => (cutscene.frames || []).map((frame) => ({ ...frame, cutsceneId: cutscene.id, cutsceneSlot: cutscene.slot }))); }
function fromSuggestion(value, title, scenes, definition) { return { title, stageDescription: value.stageDescription || title, difficulty: value.difficulty || "NORMAL", actId: value.actId, stageIndex: value.stageIndex, stageUiNumber: value.stageUiNumber, unlockDungeonId: value.unlockDungeonId, stageId: value.stageId, dungeonId: value.dungeonId, cutsceneId: value.cutsceneId, stageStrId: value.stageStrId, dungeonStrId: value.dungeonStrId, cutsceneStrId: value.cutsceneStrId, background: value.background || "CAFE", music: "", stageCharacter: value.stageCharacter || "NKM_UNIT_C_POLICE_LEE_YUMI", actBackground: value.actBackground || definition?.actBackground || "", episodeThumbnail: value.episodeThumbnail || definition?.thumbnail || "", dungeonIcon: value.dungeonIcon || "NKM_NPC_CUT_SCENE", scenes }; }
function fromAuthoring(stage) { const ui = stage.clientUi || {}, base = stage.base || {}, readOnly = stage.cutsceneReadOnly === true; return { operation: stage.operation, baseObjectId: base.objectId, baseSnapshot: base.snapshot, sourceObjectId: stage.operation === "clone" ? base.objectId : undefined, sourceStageId: base.stageId, sourceEpisodeId: base.episodeId, sourceCategory: base.category, sourceDifficulty: base.difficulty, cutsceneReadOnly: readOnly, forkCutscenes: stage.forkCutscenes === true, unlockRequirementType: stage.unlockRequirementType, title: stage.title, stageDescription: stage.stageDescription || ui.description || stage.title, difficulty: stage.placement.difficulty || "NORMAL", actId: stage.placement.actId, stageIndex: stage.placement.stageIndex, stageUiNumber: stage.placement.stageUiNumber, unlockDungeonId: stage.unlockDungeonId || 0, stageId: stage.ids.stageId, dungeonId: stage.ids.dungeonId, cutsceneId: stage.ids.cutsceneId || 0, stageStrId: stage.ids.stageStrId, dungeonStrId: stage.ids.dungeonStrId, cutsceneStrId: stage.ids.cutsceneStrId || "", background: stage.background || "CAFE", music: stage.music || "", stageCharacter: stage.stageCharacter || ui.avatar || "NKM_UNIT_C_POLICE_LEE_YUMI", actBackground: ui.actBackground || "", episodeThumbnail: ui.episodeThumbnail || "", dungeonIcon: ui.dungeonIcon || "", scenes: readOnly ? [] : stage.scenes || [blankScene()], previewScenes: readOnly ? stage.previewScenes || [] : undefined }; }
function setPath(root, path, value) { const next = structuredClone(root); let target = next; for (let index = 0; index < path.length - 1; index += 1) target = target[path[index]]; target[path.at(-1)] = value; return next; }
function isSelected(node, selected) { return selected && node.source === selected.source && (node.source === "mod" ? node.index === selected.index : node.stage.stageId === selected.stage.stageId && node.stage.difficulty === selected.stage.difficulty); }
function positionNodes(nodes, pan) { const step = 220, width = 170, span = Math.max(0, (nodes.length - 1) * step); const start = Math.max(80, (1280 - span - width) / 2); return nodes.map((node, index) => ({ ...node, x: start + index * step + pan.x, y: 290 + pan.y, w: width, h: 110 })); }
function drawStageCanvas(canvas, nodes) { const context = canvas?.getContext("2d"); if (!context) return; context.clearRect(0, 0, canvas.width, canvas.height); context.fillStyle = "#070d14"; context.fillRect(0, 0, canvas.width, canvas.height); if (nodes.length < 2) return; context.strokeStyle = "#d7e4ee"; context.lineWidth = 3; context.beginPath(); nodes.forEach((node, index) => { const x = node.x + node.w / 2, y = node.y + node.h / 2; if (index) context.lineTo(x, y); else context.moveTo(x, y); }); context.stroke(); }
function navigateNode(direction, layout, stages, selected, select) { const overrides = new Set(stages.filter((stage) => stage.operation === "override").map((stage) => `${stage.stageId}:${stage.difficulty}`)); const nodes = (layout?.stages || []).filter((stage) => !overrides.has(`${stage.stageId}:${stage.difficulty}`)).map((stage) => ({ source: "base", stage })).concat(stages.map((stage, index) => ({ source: "mod", stage, index }))).sort((a, b) => Number(a.stage.difficulty === "HARD") - Number(b.stage.difficulty === "HARD") || a.stage.actId - b.stage.actId || a.stage.stageIndex - b.stage.stageIndex); const index = nodes.findIndex((node) => isSelected(node, selected)); const target = nodes[Math.max(0, Math.min(nodes.length - 1, (index < 0 ? 0 : index) + direction))]; if (target) select(target); }
function assetRoute(catalog, kind, id) { const needle = String(id || "").toUpperCase(); if (!needle) return ""; if (kind === "actor") { const actor = (catalog?.actors || []).find((item) => String(item.id).toUpperCase() === needle); if (actor?.previewAsset) return `asset?path=${encodeURIComponent(actor.previewAsset)}`; return catalog?.previewAssets?.[needle] || ""; } const key = kind === "voice" ? "voices" : kind === "music" ? "music" : `${kind}s`; const item = (catalog?.[key] || []).find((value) => String(typeof value === "string" ? value : value.id).toUpperCase() === needle); return item && typeof item !== "string" && item.path ? `asset?path=${encodeURIComponent(item.path)}` : ""; }
function routeUrl(basePath, route) { if (!route) return ""; if (/^(https?:|data:|blob:|\/)/.test(route)) return route; return `${basePath}/api/${route}`; }
function loadImage(src) { return new Promise((resolve) => { if (!src) return resolve(null); const image = new Image(); image.onload = () => resolve(image); image.onerror = () => resolve(null); image.src = src; }); }
function drawWebGlScene(canvas, background, actors, dimActors) { const gl = canvas?.getContext("webgl", { alpha: true, premultipliedAlpha: false }); if (!gl) return; const shader = (type, source) => { const value = gl.createShader(type); gl.shaderSource(value, source); gl.compileShader(value); return value; }; const program = gl.createProgram(); gl.attachShader(program, shader(gl.VERTEX_SHADER, "attribute vec2 p;attribute vec2 t;varying vec2 v;void main(){gl_Position=vec4(p,0.0,1.0);v=t;}")); gl.attachShader(program, shader(gl.FRAGMENT_SHADER, "precision mediump float;uniform sampler2D image;uniform float dim;varying vec2 v;void main(){vec4 c=texture2D(image,v);float g=dot(c.rgb,vec3(.299,.587,.114));c.rgb=mix(c.rgb,vec3(g)*.55,dim);gl_FragColor=c;}")); gl.linkProgram(program); gl.useProgram(program); const buffer = gl.createBuffer(); gl.bindBuffer(gl.ARRAY_BUFFER, buffer); const p = gl.getAttribLocation(program, "p"), t = gl.getAttribLocation(program, "t"), dim = gl.getUniformLocation(program, "dim"); gl.enableVertexAttribArray(p); gl.enableVertexAttribArray(t); gl.vertexAttribPointer(p, 2, gl.FLOAT, false, 16, 0); gl.vertexAttribPointer(t, 2, gl.FLOAT, false, 16, 8); gl.enable(gl.BLEND); gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA); gl.viewport(0, 0, 1280, 720); gl.clearColor(.02, .03, .05, 1); gl.clear(gl.COLOR_BUFFER_BIT); const draw = (image, x, y, w, h, fade) => { if (!image) return; const texture = gl.createTexture(); gl.bindTexture(gl.TEXTURE_2D, texture); gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true); gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE); gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE); gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR); gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, image); const left = x / 640 - 1, right = (x + w) / 640 - 1, top = 1 - y / 360, bottom = 1 - (y + h) / 360; gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([left, bottom, 0, 0, right, bottom, 1, 0, left, top, 0, 1, left, top, 0, 1, right, bottom, 1, 0, right, top, 1, 1]), gl.STREAM_DRAW); gl.uniform1f(dim, fade ? 1 : 0); gl.drawArrays(gl.TRIANGLES, 0, 6); gl.deleteTexture(texture); }; draw(background, 0, 0, 1280, 720, false); actors.forEach((actor) => { const center = actor.position === "L" ? 270 : actor.position === "R" ? 1010 : 640; draw(actor.image, center - 180, 245, 360, 360, dimActors); }); gl.deleteBuffer(buffer); gl.deleteProgram(program); }
